# Generated by Django 5.1.1 on 2024-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_age_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('NL', 'Newsletter'), ('Gl', 'Google'), ('YT', 'Youtube')], max_length=100),
        ),
    ]
